### ISSUE TITLE
Issue with booktitle on github

### ISSUE THREAD

**Issue by twitwi** [vdplasthijs/py_bibtex_to_cff_converter#1]
Thanks for sharing this converter.
I observed that github does not use the booktitle and it was ok if replaced with conference.title

    -  booktitle: "Proceedings of the AAAI Conference on Artificial Intelligence"
    +  conference:
    +    name: "Proceedings of the AAAI Conference on Artificial Intelligence"

Github then regenerates a "series" attribute (that you have in your examples, but that I did not have).
I guess if used series in place of booktitle, it would have worked for me.

I don't know the complete exact semantics of bibtex but I had rarely seen "series" and very often "booktitle".

I'll probably make a PR to transform the booktitle (unless it is rather a github bug...).
Would you have recommendations on whether booktitle should be mapped to conference.name or series?

**Comment by vdplasthijs** [comment]
Thanks for your contribution! I didn't realise, yep that's a good idea. Github citations are a bit frustrating because it doesn't pick up many of the entries in the .cff file.. If you'd like to do a PR that would be great. Maybe `series` is a bit more fitting? Perhaps you could also keep the `booktitle` entry for clarity - it will just be ignored by github - and put the `series` entry under `preferred-citation`..? Just a suggestion, whatever you think is best. I'll merge your PR when I see it, thanks very much!!
